version: '3.8'

services:
  youtube-downloader:
    build: .
    container_name: youtube-downloader
    ports:
      - "${HOST_PORT:-8080}:80"
    volumes:
      - ${DOWNLOAD_PATH:-./downloads}:/var/www/html/P/youtube
      - .:/var/www/html
    environment:
      - APACHE_DOCUMENT_ROOT=/var/www/html
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
    restart: unless-stopped
    networks:
      - youtube-network

networks:
  youtube-network:
    driver: bridge

volumes:
  downloads:
    driver: local